# This is a basic workflow to help you get started with Actions

name: Zip and hash release

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Zip folder
        run: |
          cd ../
          rm -rf BeachboyCustomRoleplayPack.zip
          zip -r BeachboyCustomRoleplayPack.zip ./BeachboyCustomRoleplayPack/*

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: ${{ github.run_number }}
          release_name: ${{ github.run_number }}

      - name: Upload zip to release
        uses: actions/upload-release-asset@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./BeachboyCustomRoleplayPack.zip
          asset_name: BeachboyCustomRoleplayPack.zip
          asset_content_type: application/zip
